### ISSUE TITLE
A bug in Nodejs environment...???

### ISSUE THREAD

**Issue by PhanHoangAnh** [phpmycoder/cryptico-node#1]
I am using cryptico and it was installed via npm - nodejs.
I try follow your snip-code  as bellow 
an suddenly get a error:
I really surprised..is cryptico just for browser only...???
Code: 
var cryptico = require('cryptico')

// The passphrase used to repeatably generate this RSA key. 
var PassPhrase = "The Moon is a Harsh Mistress."; 

// The length of the RSA key, in bits. 
var Bits = 1024; 

var MattsRSAkey = cryptico.generateRSAKey(PassPhrase, Bits);

var MattsPublicKeyString = cryptico.publicKeyString(MattsRSAkey);  

console.log(' publicKey: ', MattsPublicKeyString);

var PlainText = "Matt, I need you to help me with my Starcraft strategy.";

var EncryptionResult = cryptico.encrypt(PlainText, MattsPublicKeyString);

console.log(' PlainText: ', PlainText);

console.log('EncryptionResult: ', EncryptionResult);

var DecryptionResult = cryptico.decrypt(EncryptionResult, MattsRSAkey);

Error
 publicKey:  amm3Tx0RqSd4St+34UjlX2ILusFGc4xKh+3wrXSfmEkejnylA59QYW+aTL+rwrs5pX+DVLw9yqGzLPTfzxb+Yw==
 PlainText:  Matt, I need you to help me with my Starcraft strategy.
EncryptionResult:  { status: 'success',
  cipher: 'Z0XnO+UcENK+BMo67I3sQBvBNyg1hwdy2qaoPYeVHOL9z5MqL//8CWEucavpV+isN0jreChYQfzLg5DyD1C/Jw==?DyrgCSDmmnUbJ8BP0htAcx0TGZAGb8G/EXIJsDpnFaYlEiUEseNyRmHiJux3Lu4hmAAmo0IMFYhHcUN0M2TFESimUV7e3BTdm+GGBHu/B6E=' }
D:\Labs\Web\SampleCode\Factory\node_modules\cryptico\lib\cryptico.js:2956
        var cipherblock = ciphertext.split("?");
                                     ^
TypeError: undefined is not a function
    at Object.module.exports.my.decrypt (D:\Labs\Web\SampleCode\Factory\node_modules\cryptico\lib\cryptico.js:2956:38)
    at Object.<anonymous> (D:\Labs\Web\SampleCode\Factory\index.js:86:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
11 Jul 19:53:14 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by queval-j** [comment]
Hi @PhanHoangAnh,

You've done a small mistake in your code. If you take a look to the function "my.decrypt" (located at : node_modules/cryptico/lib/cryptico.js, line 2956). The function expects to have 2 arguments : "cypherText" and "key".

In your case you send an "object" instead of the cipher text generated. Your code fixed : 

``` javascript
var cryptico = require('cryptico');
var PassPhrase = "The Moon is a Harsh Mistress."; // The passphrase used to repeatably generate this RSA key.
var Bits = 1024; // The length of the RSA key, in bits.

var MattsRSAkey = cryptico.generateRSAKey(PassPhrase, Bits);
var MattsPublicKeyString = cryptico.publicKeyString(MattsRSAkey);
console.log(' publicKey: ', MattsPublicKeyString);

var PlainText = "Matt, I need you to help me with my Starcraft strategy.";
var EncryptionResult = cryptico.encrypt(PlainText, MattsPublicKeyString);
console.log(' PlainText: ', PlainText);
console.log('EncryptionResult: ', EncryptionResult);

var DecryptionResult = cryptico.decrypt(EncryptionResult.cipher, MattsRSAkey);
console.log('PlainText:', DecryptionResult.plaintext);
console.log(DecryptionResult);
```

Result : 

``` bash
queval_j$ node -v
v6.6.0
queval_j$ node index.js
 publicKey:  uXjrkGqe5WuS7zsTg6Z9DuS8cXLFz38ue+xrFzxrcQJCXtVccCoUFP2qH/AQ4qMvxxvqkSYBpRm1R5a4/NdQ5ei8sE8gfZEq7dlcR+gOSv3nnS4/CX1n5Z5m8bvFPF0lSZnYQ23xlyjXTaNacmV0IuZbqWd4j9LfdAKq5dvDaoE=
 PlainText:  Matt, I need you to help me with my Starcraft strategy.
EncryptionResult:  { status: 'success',
  cipher: 'Sl+MNp8sBg2w9noFuiNkI1thiaF3Hm1ezpKueAccwlj9JfL4V4vV7p3MbfaTKqMNVa/cBzC9wSpef9stHfmhY1iP9wooktp5ZjANVD5O3W8NLnsTWjT5EZ9jGkkdwcH3OJTw188k8u5R4W0+7uBbCbBqnu1eoitSuNhRMn8p+0U=?THJJHPfMGSODXrIw8ZxQMfJghSbCdtuFIDV0yzQoRyHmZyU+UpiInfVQBrSV/vty7l05X4ZagH44sXvlh6UFYAh9QldbwjDxCJbTP6PeSwA=' }
PlainText: Matt, I need you to help me with my Starcraft strategy.
{ status: 'success',
  plaintext: 'Matt, I need you to help me with my Starcraft strategy.',
  signature: 'unsigned' }
queval_j$ 
```

**Comment by PhanHoangAnh** [comment]
Thank..
